export const relationshipQuestions: string[] = [
    "Co było Twoim pierwszym wrażeniem na mój temat?",
    "Jakie są według Ciebie trzy najważniejsze elementy udanego związku?",
    "Jakie cechy uważasz za najważniejsze u partnera?",
    "Jakie są Twoje największe obawy dotyczące naszego związku?",
    "Czego najbardziej oczekujesz od naszego związku?",
    "Jak widzisz nasz związek za pięć lat?",
    "Jak radzisz sobie z konfliktami w związku?",
    "Jakie wartości są dla Ciebie najważniejsze w relacji?",
    "Czy wierzysz w miłość od pierwszego wejrzenia?",
    "Jakie jest Twoje najważniejsze marzenie dotyczące naszego związku?",
    "Jak wolisz rozmawiać o trudnych tematach?",
    "Co mogę zrobić, aby lepiej Cię zrozumieć?",
    "Jak mogę pomóc Ci czuć się bardziej swobodnie w wyrażaniu swoich emocji?",
    "Jak reagujesz, gdy czujesz, że nie jesteś słuchany?",
    "Jakie jest Twoje podejście do rozwiązywania problemów?",
    "Czy czujesz, że możesz być ze mną całkowicie szczery?",
    "Co najbardziej lubisz w naszej komunikacji?",
    "Czy są tematy, które czujesz, że są dla Ciebie trudne do poruszenia?",
    "Jak radzisz sobie z uczuciem zazdrości?",
    "Co najbardziej doceniasz w naszej relacji?",
    "Jakie są Twoje trzy największe cele życiowe?",
    "Co chcesz osiągnąć w ciągu najbliższych pięciu lat?",
    "Jakie jest Twoje największe marzenie dotyczące życia osobistego?",
    "Czy jest coś, czego jeszcze o Tobie nie wiem?",
    "Jakie są Twoje priorytety w życiu?",
    "Jakie są Twoje zainteresowania, które chciałbyś zgłębić?",
    "Czy masz jakieś marzenia, które byłyby dla Ciebie zaskakujące?",
    "Jakie jest Twoje podejście do sukcesu i porażki?",
    "Czy czujesz, że masz odpowiednią równowagę między pracą a życiem osobistym?",
    "Co najbardziej motywuje Cię do działania?",
    "Co sprawia, że czujesz się spełniony?",
    "Jakie są Twoje największe obawy dotyczące przyszłości?",
    "Jak widzisz swoją rolę w naszej rodzinie?",
    "Ilu dzieci chciałbyś mieć?",
    "Jakie są Twoje oczekiwania wobec rodziny?",
    "Jakie wartości chciałbyś przekazać naszym dzieciom?",
    "Jakie są Twoje wspomnienia z dzieciństwa, które chciałbyś odtworzyć dla naszych dzieci?",
    "Jakie są Twoje obawy dotyczące rodzicielstwa?",
    "Jakie tradycje rodzinne chciałbyś kontynuować?",
    "Jak ważna jest dla Ciebie bliskość z rodziną?",
    "Czy wolisz większe, czy mniejsze rodziny?",
    "Jak radzisz sobie z problemami w relacjach rodzinnych?",
    "Czy chciałbyś, abyśmy mieszkali blisko naszych rodzin?",
    "Jakie jest Twoje podejście do finansów w związku?",
    "Czy wolisz, abyśmy mieli wspólne konto bankowe czy osobne?",
    "Jakie są Twoje finansowe cele na przyszłość?",
    "Jakie są Twoje przemyślenia na temat oszczędzania i inwestowania?",
    "Czy masz jakieś wydatki, które uważasz za istotne dla Twojego szczęścia?",
    "Jakie są Twoje obawy dotyczące finansów?",
    "Czy chciałbyś mieć kontrolę nad finansami w związku?",
    "Czy jest coś, na co chciałbyś wydać dużą sumę pieniędzy?",
    "Jakie są Twoje plany emerytalne?",
    "Jak ważne są dla Ciebie inwestycje?",
    "Czy uważasz, że mamy dobrą równowagę w podejściu do pieniędzy?",
    "Czy masz jakiekolwiek długi, o których chciałbyś porozmawiać?",
    "Jakie są Twoje cele związane z podróżowaniem?",
    "Jakie jest Twoje wymarzone miejsce na wakacje?",
    "Jakie miejsca chciałbyś odwiedzić razem?",
    "Czy wolisz spontaniczne podróże czy planowane z wyprzedzeniem?",
    "Jakie przygody chciałbyś przeżyć w naszym związku?",
    "Co sprawia, że podróżowanie jest dla Ciebie ekscytujące?",
    "Czy jest coś, co chciałbyś zrobić po raz pierwszy w podróży?",
    "Jakie są Twoje najlepsze wspomnienia z podróży?",
    "Jak radzisz sobie z nieplanowanymi sytuacjami podczas podróży?",
    "Jakie są Twoje cele związane ze zdrowiem i kondycją?",
    "Czy chciałbyś, abyśmy uprawiali razem sport?",
    "Jakie są Twoje nawyki zdrowotne?",
    "Czy są jakieś aktywności, które chciałbyś wypróbować?",
    "Jak radzisz sobie ze stresem?",
    "Czy chciałbyś medytować lub ćwiczyć mindfulness?",
    "Jakie są Twoje cele zdrowotne na przyszłość?",
    "Jakie są Twoje ulubione sposoby na relaks?",
    "Czy uważasz, że masz zdrowe nawyki żywieniowe?",
    "Czy uważasz, że mamy dobrą równowagę między pracą a relaksem?",
    "Jakie jest Twoje podejście do bliskości fizycznej w związku?",
    "Jakie są Twoje oczekiwania dotyczące seksu w związku?",
    "Co sprawia, że czujesz się bezpiecznie podczas intymnych chwil?",
    "Czy czujesz, że nasze potrzeby w tej sferze są dobrze dopasowane?",
    "Jakie są Twoje najważniejsze wartości w kontekście intymności?",
    "Czy jest coś, co chciałbyś wypróbować w naszym życiu intymnym?",
    "Jak często potrzebujesz bliskości fizycznej?",
    "Czy czujesz, że nasze życie intymne spełnia Twoje oczekiwania?",
    "Jakie są Twoje preferencje dotyczące romantycznych gestów?",
    "Co mogę zrobić, abyś czuł się bardziej doceniony?",
    "Jakie są Twoje potrzeby w zakresie dotyku i bliskości?",
    "Co według Ciebie sprawia, że intymność jest satysfakcjonująca?",
    "Czy jest coś, co chciałbyś omówić na temat naszej bliskości?",
    "Jakie są Twoje długoterminowe cele w związku?",
    "Co jest dla Ciebie najważniejsze w naszej przyszłości?",
    "Jakie są Twoje oczekiwania wobec wspólnego starzenia się?",
    "Czy chciałbyś, abyśmy mieli wspólne hobby?",
    "Co sprawia, że czujesz się kochany i doceniony?",
    "Jakie są Twoje marzenia na temat przyszłości?",
    "Jakie są Twoje obawy dotyczące naszej przyszłości?",
    "Czy czujesz, że nasze cele życiowe są zgodne?",
    "Jakie są Twoje nadzieje na wspólne życie za dziesięć lat?"
];
